import {
  mdiGoogleAnalytics,
  mdiAccount,
  mdiArrowDown,
  mdiHelpCircleOutline,
  mdiPlusCircle,
  mdiMinusCircle,
  mdiLock,
  mdiLockOpen,
  mdiCloseThick,
  mdiInformationVariant,
  mdiInformation,
  mdiPlus,
  mdiChevronRight,
  mdiChevronDown,
  mdiSubdirectoryArrowRight,
  mdiAlert,
  mdiHelpCircle,
  mdiCheck,
} from "@mdi/js";

export default {
  mdiGoogleAnalytics,
  mdiHelpCircleOutline,
  mdiAccount,
  mdiArrowDown,
  mdiPlusCircle,
  mdiMinusCircle,
  mdiLock,
  mdiLockOpen,
  mdiCloseThick,
  mdiInformationVariant,
  mdiPlus,
  mdiChevronRight,
  mdiChevronDown,
  mdiInformation,
  mdiSubdirectoryArrowRight,
  mdiAlert,
  mdiHelpCircle,
  mdiCheck,
};
